name = "api"
type = "javascript"
zone_id = ""
account_id = "1bda26fe457ea7a9dcd193e268e07770"
workers_dev = true
compatibility_date = "2022-04-01"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
